### ISSUE TITLE
🚧Update Readme

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/VersionMiner#131]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

## **Description**

We are in the process of rationalizing ReadMe across all GitHub Actions (GHA). This includes:

Making sure all sections are in this order:
  - Logo 
  - Repo Name
  - Badges
  - What is it
      -  Add'l info as a TLDR
      - Usage Cases as a TLDR
  - Note block (Quick Note)
  - Quick Example
  - Action Input
  - Action Output
  - Examples
  - Contrib/Funding (after combined like in lib section)
  - Maintainers
  - License

### **Details of the changes to the sections are below:**
**What is it Section**
- Use what is currently in this section after spelling and grammar checks
- Make What does it do section as TLDR

**Usage Examples**
- Change to Use Cases and make TLDR 
  
**Quick Note Section** 
- Change to say Warning block instead of Quick Note

**Quick Example Section**
- Delete "more examples below" link
- Change to Example

**What does it do? Section**
- Add to What is it section as TLDR

**Action Output Section**
> **Note** This will be done by @CalvinWilkinson 

**Examples Section**
- Example 1 - make it look like BV
- Remove Quick note
- Remove "requirements"
- Example 2 - Make it look like BV
- Remove "requirements"
- Remove Quick note
- Example 3 - Make it look like BV
- Remove "requirements" 
- Remove "result"
- Example 4 - Make it look like BV
- Remove "requirements"
- Remove first result
- Make 2nd bullet item under result a note block under the "need to trim" section
  - Set the text to the example below:
    ```txt
    Click here to get more information about the default variable `github.ref` used in the example below.
    ```
- Remove "more examples below" link
**Contribution Section**
- Change title to Contributing
- Add section, make general (don't use repo or project name)
- To learn how to contribute your time click here (link to Contributing doc). To learn how to contribute funds to this project, click here.

**Maintainers Section**
- Add section like in Velaptor

**License Section**
- Add section just like in Velaptor; with badges etc.

### **Other**
 - Double checking spelling/grammar
 - Making wording the same in similar sections
 - Remove any TODO comments
 - Verify all links work and point correctly
 - Remove Back to the Top! section at the very end
 - CMW to make examples clickable on input table

## Acceptance Criteria
- [x] Move the info about the `version-keys` input in the _**TLDR - Additional Info**_ section into the table.
    > **Note** This will be done by @CalvinWilkinson 
- [x] Make sure all sections are in this order:
    - [x] Logo 
    - [x] Repo Name
    - [x] Badges
    - [x] What is it
       - [x] TLDR Add'l info
       - [x] TLDR Use Cases
    - [x] Note block (Quick note)
    - [x] Example (Quick Example)
    - [x] Action Input
    - [x] Action Output
    - [x] Examples
    - [x] Contributing
    - [x] Maintainers
    - [x] License
- [x] Perform spelling and grammar checks in the **What is it** section
- [x] Change the **Quick Note** section to Note block 
- [x] Remove the **more examples below** link 
- [x]  Example 1 - make it look like BV
- [x] Remove Quick note
- [x] Remove "requirements"
  - [x] Example 2 - Make it look like BV
  - [x] Remove "requirements"
  - [x] Remove Quick note
  - [x] Example 3 - Make it look like BV
  - [x] Remove "requirements" 
  - [x] Remove "result"
  - [x] Example 4 - Make it look like BV
  - [x] Remove "requirements"
  - [x] Remove first result
  - [x] Make 2nd bullet item under result a note block under the "need to trim" section
- [x] Move the **What does it do** section to What is it section
- [x] An **Action Outputs** section is created below the **Action Inputs** table.
    > **Note** This will be done by @CalvinWilkinson 
- [x] Add  **Contributing Section** like in Velaptor
- [x] Add **Maintainers** section like in Velaptor
- [x] Add **License** section just like in Velaptor; with badges
 - [x] Double check spelling/grammar
 - [x] Making wording the same in similar sections like in Velaptor or GotNuget
 - [x] Remove any TODO comments
 - [x] Verify all links work and point correctly
 - [x]  Remove Back to the Top! 
 - [x] Make sure all sections have the same emoji's as Velaptor/GotNuget
 - [x] CMW to do clickable example links

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
