### ISSUE TITLE
🚧Change branching model and workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#135]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Change the branching model and workflow of the project.  Currently, this project is with a more complicated **_GitFlow_** branching model and workflow.  

This has proven to be more complicated than what this project requires. This will require changing the workflows to properly validate branches, versions, etc.

**Branches:**
The only branches we will have are `master` and `feature/[0-9]-*` branches.  What will signify that we are in preview is the version value itself. 

**Tags:**
The tags will also contain the same syntax as the versions.  If the latest tag that we have released is a preview tag, then we also must currently be in preview.

#### **Work To Perform**
**Workflows**
1. Build status check workflow
    - Update the branches filter in the workflow event section to only have the `master` branch 
2. Unit test status check workflow
    - Update the branches filter in the workflow event section to only have the `master` branch 
2. Release Workflow
    > **Note** Calvin needs to do some research on this to see if he can automate the release to the marketplace
    - This workflow is only executed manually
    - The release workflow can only run if it is a `master` branch.
    - Use **_VersionMiner_** action to pull version from project file
    - Use the reusable workflows to build and test the project
    - Look into the GitHub CLI to see if issue number validation can be performed
    - Use the _**Get Build Config**_ step from the _**build-status-check.yml**_ workflow
3. Need to update the SDK version in both workflows.  The version is currently _**v7.0.101**_ and needs to be updated to _**v7.0.203**_.
    - _**build-status-check.yml**_ - Delete this
      ```yml
      env:
        NET_SDK_VERSION: 7.0.101
      ```
    - Delete the `get_sdk_version` job . . 
    - Update the `build_project` and `build_tests_project` jobs to use a hard coded SDK version instead of the interpolated variable inputs.
      ```diff
      - net-sdk-version: ${{ needs.get_sdk_version.outputs.sdk-version }}
      + net-sdk-version: 7.0.203
      ```
    - _**unit-testing-status-check.yml**_
    Update the hard coded version of the SDK version to _**7.0.203**_.  It is in the `run_tests` job.
      ```diff
      -    net-sdk-version: 7.0.101
      -    net-sdk-version: 7.0.203
      ```
**Documentation:**
1. Need to create a version of the organizational contribution document that will be for GitHub actions.
2. Update the README contribution section to point to the new contribution document

**Other:** (Calvin)
1. Figure out how to perform a release to the GitHub action marketplace.
    > **Note** This involves creating a GitHub release, but it is unknown how to set that GitHub release to the marketplace.  There is a possibility that since the project is an action that contains an _**action.yml**_ file, that it will just auto set to the marketplace upon release creation.

---

### Acceptance Criteria

- [x] _**build-status-check.yml**_ workflow updated
- [x] _**unit-testing-status-check.yml**_ workflow updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
