### ISSUE TITLE
✔️Convert action to .NET

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#14]
### I have done the items below . . .

- [X] I have created a title but left the ✔️ emoji behind.

### Description

Convert the GitHub action from typescript/javascript style to C# style project.
Use the **NETGitHubActionSample** project as a starter project.

**Resources:**
- [Get Repo Content API](https://docs.github.com/en/rest/repos/contents#get-repository-content)

### Acceptance Criteria

**This issue is finished when:**
- [x] Abstract the GitHub action functionality if possible
- [x] Create unit tests
- [x] All of the same behavior and functions should be migrated over to the new project style
- [x] Use the C# HTTP client [Rest Sharp](https://github.com/restsharp/RestSharp)

**Inputs To Create:**
  - [x] `repo-owner: string` implemented
    - **Required: _true_**
    - The owner of the repository

---

  - [x] `repo-name: string` implemented
    - **Required: _true_**
    - The name of the repository

---

  - [x] `branch-name: string` implemented
    - **Required: _true_**
    - The name of the branch where the file lives that contains the version

---

  - [x] `file-path: string` implemented
    - The path to the file relative to the root of the repository

---

  - [x] `file-type: string` implemented
    - **Required: _true_**
    - `xml` will currently be the only value that can be used
    - Any other value will throw an exception and fail the action

---

   - [x] `version-keys: string-array` implemented
    - **Required: _true_**
    - The key(s) that can possibly hold the version to pull from the file.  Example _**csproj**_ values are `Version`, `FileVersion`, and `AssemblyVersion` in file.
      - [x] If more than one key, each key will be checked until a key is found with a value.  The first key to have a value, will the be value returned as an output.
    - **Fail Examples(if `fail-with-no-version` is `true`):**
        - [x] No keys have a value - prints error

---

  - [x] `case-sensitive-keys: bool` implemented
    - **Required: _false_**
    - **Default: _true_**
    - If true, then the keys in the `version-keys` input are case sensitive.

---

  - [x] `fail-on-missing-key: bool` implemented
    - **Required: _false_**
    - **Default: _true_**
    - [x] All keys must exist if called out in the array of `version-keys`.

---

  - [x] `fail-on-key-mismatch: bool` implemented
    - **Required: _false_**
    - **Default: _true_**
    - [x] If `true` and the `version-keys` have more than one item, and they all do not match, then the action will fail.
    - [x] If all keys exist and all are empty, this is a match and a failure will not occur.
    - **Fail Examples:**
      - [x] The `Version` and `FileVersion` keys are in the array, but the `FileVersion` does not exist.
      - [x] The `Version` and `FileVersion` keys are in the array, but the `FileVersion` value does not match the `Version` value.

---

  - [x] `fail-with-no-version: true` implemented
    - **Required: _false_**
    - **Default: _true_**
    - If `true`, then the action will fail if no version exists in the file.

---

**Outputs To Create:**
- [x] `version` implemented
  - This is the version pulled from the data.  For example, a **_csproj_** file

**Example Use:**
``` yaml
- name: Get Version From Project File
  id: proj-file-version
  uses: KinsonDigital/VersionMiner@v1.2.3
  with:
    repo-owner: KinsonDigital
    repo-name: VersionMiner
    branch-name: master
    file-type: xml
    file-path: VersionMiner/VersionMinor.csproj
    version-keys: [Version, FileVersion]
    case-sensitive-keys: true
    fail-on-missing-key: true
    fail-on-key-mismatch: true
    fail-with-no-version: true
```

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [x]  Running manual testing using the [Nektos Act](https://github.com/nektos/act) setup to run the action locally
