### ISSUE TITLE
🚧Create release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#141]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a release workflow to run some checks, build, run tests, and then perform a GitHub release.

Make sure to have the release set to the _**latest**_ release.

Look [here](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release) at the REST API docs for information.

This should be done using the [GH Release (softprops)](https://github.com/marketplace/actions/gh-release) GitHub action from the marketplace.

After doing some digging, you cannot set releases to be the latest if it is **_draft_** or **_prerelease_**.  So when the action is in preview, the release to the marketplace will have to be manual.  Once we are v1.0, setting the releases are set to the latest by default and we will not have to manually set it to the marketplace.

### Acceptance Criteria

- [x] Release workflow created
    - [x] Only ran manually
    - [x] Checks to make sure that it is being run on the master branch only
    - [x] Pulls the version from the csproj file
    - [x] Use the version to make sure a tag that matches the version does not already exist
    - [x] Check that the release notes for the given version exist
    - [x] Run build
    - [x] Run tests
    - [x] Perform GitHub release using GitHub action

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
