### ISSUE TITLE
🚧Fix README badges

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#147]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the readme badges by updating the production and preview badges.

1. Update the production badge to be a build status check badge
    - This badge will point to the _**build-pr-status-check.yml**_ workflow.
    - Should look like this 👉🏻<img width="105" alt="image" src="https://github.com/KinsonDigital/VersionMiner/assets/85414302/5c2e14f1-c5ee-42cd-a76b-f5ea46dc1b4e">
2. Update the preview badge to be a unit tests status check badge
    - This badge will point to the _**unit-testing-status-check.yml**_ workflow.
    - Should look like this 👉🏻<img width="97" alt="image" src="https://github.com/KinsonDigital/VersionMiner/assets/85414302/dfe8e814-bdca-41d5-947c-61bfc62fd00a">
3. Both badges should use the color **_2F8840_**.
    > **Note** This is a HEX color value.  This is what you use in the website when building the badge

Badges can be built using [shields.io](https://shields.io/)

## **Current Badge Setup:**
![image](https://github.com/KinsonDigital/VersionMiner/assets/85414302/96d3b238-197c-4c4c-a74b-3aa0ec0c6547)

### Acceptance Criteria

- [x] Old prod badge changed to a build status check badge
- [x] Old preview badge changed to a test status check badge

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
