### ISSUE TITLE
🚧Release as prod version

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#148]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Release the action to the marketplace as a production version.

All that needs to be done is to simply update the version from a preview version to a production version.
This means simply changing the version from _**v1.0.0-preview.5**_ to **v1.0.0-preview.6**.

Once complete, merge the feature branch and then do a production release.

### Acceptance Criteria

- [x] Version updated to production version

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
