### ISSUE TITLE
✔️Create a bug issue template

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#16]
### I have done the items below . . .

- [X] I have created a title but left the ✔️ emoji behind.

### Description

Create a bug issue template.

Use **Velaptor** issue template as a guide.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Issue template created

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [ ] Issue linked to the proper project

**Comment by nebulahh** [comment]
can you link to Velaptor issue template cos i cant find it through google. 

will the link to Velaptor issue template be included in the template or thats what i am using

**Comment by CalvinWilkinson** [comment]
I am so sorry.  I see that you probably oicked this issue up because it has a good first issue label on it.  I did not mean to add this as a label.

This GitHub action is in the middle of a rewrite from Typescript to C#.  🙂

Thank you so much for trying to help!!

I do have some good first issues for Velaptor if you want to try some of those!!

Check this out if you would like. 🙂
[Velaptor Good First Issues](https://github.com/KinsonDigital/Velaptor/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

If yiu have any questions, don't hesitate to ask.

**Comment by CalvinWilkinson** [comment]
Issue Closed.  This was implemented in another issue.  Issue is unknown but it is already implemented
