### ISSUE TITLE
🚧Setup integration tests status check

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#184]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Setup the integration tests to be ran as a status check.  This will require updating the `IntegrationTestsBase` class to use an environment variable with the name `CICD_TOKEN`.  This is the token that will be used to run the integration tests. 

This will require also setting up the workflow to set the environment variable to the token value so it exists for the base class to use.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
