### ISSUE TITLE
Add badges to the README file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#25]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add badges to the README file.

### Acceptance Criteria

**This issue is finished when:**
- [x] Badges added to README file
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Issue linked to the correct project.
- [x] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/VersionMiner/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/VersionMiner/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VersionMiner/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VersionMiner/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VersionMiner/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Removed dependency below.  It was not required.
- #26
