### ISSUE TITLE
🚧Add new input for trimming from start of branch

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#45]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a new input with the name `trim-start-from-branch`.
This input is a string value that would be trimmed from the beginning of the `branch-name` value.

In github, it is common to use the `${{ github.ref }}` syntax or other variations to figure out which branch the PR or workflow is running on.  This comes with the string "refs/heads" prefixed to the name of the branch.  This will give the ability for users to trim that string from the branch.

### Acceptance Criteria

**This issue is finished when:**
- [x] `trim-start-from-branch` input created
  - [x] input should not be required
  - [x] input default value should be empty
- [x] README updated with information about the input
- [x] Update solution config argument inputs.
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/VersionMiner/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/VersionMiner/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VersionMiner/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VersionMiner/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VersionMiner/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
