### ISSUE TITLE
🚧Add auth requests to integration requests

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#47]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

This issue is to implement an easy way to authenticate to GitHub when making requests using the GitHub API.
Currently, when not authenticating the HTTP request, you can only execute a maximum of 60 requests per hour.
Currently, when authenticating the HTTP request, you can execute a maximum of 5000 requests per hour when doing a user -> server request.  This includes user to a personal account or the organization your personal account owns.

Any requests that exceed that limit is rejected with a 403(FORBIDDEN) response.

### **References:**
[Rate Limit Reference](https://docs.github.com/en/rest/overview/resources-in-the-rest-api)

### **Local Test Execution Credential Storage:**
**The problem:**
The problem here is that during development, you want to execute the integration tests locally to verify that things are working correctly.  This easily gets exceeded when not authenticating the HTTP requests is what currently is being done.  Increasing the limit from 60 to 5000 will prevent development from being halted due to not being able to perform requests.

We can solve this problem by authenticating but will require some work.  First we need to create a simple console application that will give us the ability to easily create and retrieve credentials into the windows credential manager.  This application will be simple.  It will allow the passing of arguments which will be the target (credential name) that is storing the user name and password.  If the credential exists, then the password will be returned.  If it does not exist, it will display the console window to ask for a user name and password to store into the windows credential manager.  This ability will allow windows users that are executing the integration tests for the very first time, to create the credentials to be stored in the windows credential manager.  After the first time, the application will not ask to enter the credentials because they exist and they will automatically be retrieved from the windows credential manager to be used in the requests.

### **CI/CD Workflow Credential Storage:**
For this scenario, all that needs to be done is to use the GITHUB_TOKEN in the workflow which will authenticate and allow the 5000 requests per hour limit when running the workflow.   For this to happen, we need to add more inputs to the workflow to allow this to occur.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Issue linked to the correct project.
- [ ] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Issue Dependencies

- Create credential manager library
- Add a `repo-token` input to action

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/VersionMiner/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/VersionMiner/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VersionMiner/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VersionMiner/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VersionMiner/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Issue Closed without implementation

**Reason:**
Investigation revealed that you cannot enter information into windows credentials and a new approach has to be designed.
