### ISSUE TITLE
🚧Add new repo-token input

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#48]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a new input named `repo-token`.  This will be used to authenticate to GitHub when making HTTP requests to GitHub. 

This will allow the request rate limit go from 60/hour to 5000/hour.
Do not make the `repo-token` required with a default value of an empty string.  If the user decides to go this route, make sure that if a 403 forbidden is returned in regards to a rate limit, that a message is printed to the console explaining the rate limit issue.  Also explain that they can use a token and the input to solve the issue.

Also grab the rate limit information from the response headers and display the info when the rate is exceeded and when it is not.

### Acceptance Criteria

**This issue is finished when:**
- [x] Add new input named `repo-token`
- [x] ~Display error about exceeding the rate limit if it occurs.~
  - ~Should explain the issue clearly with rate limit numbers~
  - ~This will also have a link to the GitHub rate limit docs~
- [x] ~Should display the rate limit numbers on successful requests~
- [x] README documentation updated for new input
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Issue Dependencies

- KinsonDigital/GitHubData#1
- KinsonDigital/GitHubData#7
- KinsonDigital/GitHubData#33

### Related Work

- KinsonDigital/GitHubData#44

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature |  https://github.com/KinsonDigital/VersionMiner/labels/%E2%9C%A8new%20feature                       |
| Workflow Changes    | https://github.com/KinsonDigital/VersionMiner/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VersionMiner/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VersionMiner/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VersionMiner/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Did not implement the task below:
- [ ] Should display the rate limit numbers on successful requests

**Reason:**
This is due to **GitHubData** not having the required features yet to implement the functionality.  The issue below was created to implement this feature into **GitHubdata**.

- KinsonDigital/GitHubData#44
