### ISSUE TITLE
🚧Implement GitHubData library

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#49]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Implement the [GitHubData](https://github.com/KinsonDigital/GitHubData) library by adding as a nuget package and replacing all code that does the jobs that the library can do.

### Acceptance Criteria

**This issue is finished when:**
- [x] Nuget package for GitHubData added
- [x] Remove RestSharp nuget library
- [x] Code refactored to use library
- [x] Code cleaned up
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Issue Dependencies

- KinsonDigital/GitHubData#1

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%A7%A8breaking%20changes      |
| New Features         | https://github.com/KinsonDigital/VersionMiner/labels/%E2%9C%A8new%20feature                         |
| Workflow Changes    | https://github.com/KinsonDigital/VersionMiner/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VersionMiner/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VersionMiner/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VersionMiner/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
