### ISSUE TITLE
🚧Replace GitHubData lib code with OctoKit

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#75]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, for getting GitHub related data, the library [GitHubData](https://github.com/KinsonDigital/GitHubData) is being used.
Replace this with the more capable and mature Octokit library which is built by GitHub themselves.

This is going to have significant changes to the code.  Lots of code will have to be ripped out for the GitHub data to be removed and replaced with Octokit.  This will also take significant changes to the unit tests.

**Repo Token Changes:**
It has been decided to always force authentication to the repository before using this action.  The API rate limits are to limiting anyways.  This means that the input should go from **not required** to **required.**

### Acceptance Criteria

- [x] GitHubData NuGet package removed from project
- [x] GitHubData related code removed from project
- [x] Octokit NuGet packaged added to the project
- [x] Tests all adjusted for the new changes
- [x] All unit tests passing
- [x] `repo-token` is set to required
- [x] README documentation updated
  - [x] Docs updated for `repo-token` input changes
  - [x] Add note for `repo-owner` input in the input table that the value IS NOT case sensitive.
  - [x] Add note for `repo-name` input in the input table that the value IS NOT case sensitive.
  - [x] Add note for `branch-name` input in the input table that the value IS case sensitive

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
