### ISSUE TITLE
🚧Update octokit nuget package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#81]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the **octokit** nuget package from _**v2.1.0**_ to **_v3.0.0_**.

If the latest version of the package is greater than _**v3.0.0**_ when this issue is finally implemented, update the package to the latest version as long as the changes will not result in a breaking change or incompatibility change to **Version Miner**.

### Acceptance Criteria

- [x] Octokit nuget package updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
