### ISSUE TITLE
🚧Fix branch invalid and logging issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#83]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

During the check if the branch exists, the message logged to the GitHub logs when the branch is invalid and does not exist needs to be fixed.

Also, the branch is showing that it is invalid even though the `trim-start-from-branch` action input is being used with a value of  `refs/heads/`.  Check if the validation is working correctly.  The branch should of returned valid after the trim.

![image](https://user-images.githubusercontent.com/85414302/216390447-d1335af3-eff0-42e5-9144-b98b27bf1be4.png)

### Acceptance Criteria

- [x] Check what is wrong with the branch returning invalid
    - The branch is named `preview/feature/152-setup-code-coverage` of the _**Velaptor**_ project
- [x] Message logged to the GitHub log console correctly with invalid branches.
- [x] Validate that the repo owner log works correctly when invalid
- [x] Validate that the repo name log works correctly when invalid

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
