### ISSUE TITLE
🚧Create release pipeline

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#9]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Setup the project to use the new [CICD Project](https://github.com/KinsonDigital/CICD) to perform all of the CICD status check and release work.

Currently, the CICD project can only do NuGet library releases.  This project requires a standard GitHub release that is published to the GitHub marketplace.  A dependency has been added to this issue to research on how this can possibly by done.

If the research shows that it cannot be done via C# in the CICD project, then simple utilize the CICD project for everything else exception for preview and production releases which will be done manually with regular workflows.  If this is the case, research will be required to see if a GitHub marketplace release can be done only from a workflow.  This might require a particular action to do this work.

**Reference:**
[Publishing Actions](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace) could be used to do this work.

### Acceptance Criteria

**This issue is finished when:**
- [x] CICD has been implemented into this project
- [x] Releases have been figured out by using CICD or by using regular workflows

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Issue Dependencies

- KinsonDigital/CICD#111

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/VersionMiner/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/VersionMiner/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VersionMiner/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VersionMiner/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VersionMiner/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
