### ISSUE TITLE
🚧Update the actions output

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#93]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update how the custom actions output is set.

This is getting deprecated by GitHub and will be disabled soon.  This will end up breaking the CI/CD pipeline and needs to be addressed.

Info on how to use env files can be found [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

The way that this is accomplished depends on if the shell is using **powershell** or **bash**.

### **Method to determine which shell to use**
- Using environment vars, determine which OS is being used as well as parsing of the current workflow being ran.
    > **Note** The vars to use will be the `GITHUB_WORKFLOW_REF` and `RUNNER_OS`.  These combined can be used to detect which shell to use.
    - The parse the workflow, use the path from the `GITHUB_WORKFLOW_REF` variable to pull down the contents of the workflow file using an HTTP request so it can be parsed.
    - To detect which OS is being used, use the `RUNNER_OS` variable.  The possible values are `Windows`, `Linux`, `macOS`
- The idea here is to get the OS and the source for the workflow.  Parse the workflow to detect if the entire workflow OR the job that this action belongs to is explicitly using a shell.  If so, then the OS does not matter.  The `ActionOutputService` will simply use the correct syntax for the shell being used.
    > **Note** Both the global and job level shell settings will need to be checked.  A job shell setting will override a global workflow shell setting.
- Look into the [YamlDotNet](https://github.com/aaubry/YamlDotNet) NuGet package for parsing YAML into objects.
    > **Note** When prototyping, use some current YAML files for testing.
- Use the **OctoKit** library to pull down the workflow

**More Info:**
- [Environment Vars](https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system)

Determining which one to use is gonna require the ability to find out which shell is being used.

[This is the warning](https://github.com/KinsonDigital/Velaptor/actions/runs/4105239512) displayed in one of the status check logs

### Acceptance Criteria

- [x] How the action sets its output value updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/VersionMiner/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/VersionMiner/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VersionMiner/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VersionMiner/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VersionMiner/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
> **Note** When printing out what environment variables are available, it was discovered that the 2 variables `GITHUB_WORKFLOW_REF` and `RUNNER_OS` are available.  No other variables were shown that could be used to know what shell to use.
> It was also discovered that with the new way of how step outputs work, it requires it to execute in the shell but currently it is just printing text to the console.  This means we need to figure out how to execute the actual code in the shell once we figure out what shell is being used.
