### ISSUE TITLE
🚧Improve repo file data service

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/VersionMiner#94]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the `RepoFileDataService` by replacing the `IHttpClient` with an **Octokit** implementation.

The `IHttpClient` is being used to pull down the file from the repository but this should be done with **Octokit**.

Also remove the `IHttpClient` and `HttpClient` types from the code base.

### Acceptance Criteria

- [x] The `RepoFileDataService` improved and refactored
- [x] The `IHttpClient` and `HttpClient` types removed
- [x] The `HttpResponse` removed
- [x] The `DeserializedHttpResponse` removed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/VersionMiner/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/VersionMiner/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/VersionMiner/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VersionMiner/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/VersionMiner/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/VersionMiner/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
This issue is linked to the 2 PRs below:
- #97
- #100 

**Reason:** This is because the PR #97 was merged before the work was complete.  The PR #100 has been created for the same branch and linked issue to complete the work.
